#!/bin/bash

set -e

[[ -f  ~/.shconfig/tools/lib/sb-colors.sh ]] && source  ~/.shconfig/tools/lib/sb-colors.sh

echo -n -e "${BRed}WARNING!
${Red}THIS COMMAND DELETE ALL DOCKER CONTAINERS, IMAGES, VOLUMES, CACHES E.T.C.
Continue?${RCol} (Type y/n): "
read CONFIRM

if [[ ! "$CONFIRM" == "y" ]]; then
    echo "


Cancel!"
    exit
fi

docker system prune --force --all
docker system prune --force --volumes


echo -n -e "

${Gre}Done!${RCol}

Result:
"

docker system df
