#!/bin/bash

set -e

[[ -f  ~/.shconfig/tools/lib/sb-colors.sh ]] && source  ~/.shconfig/tools/lib/sb-colors.sh

echoDone() {
	echo -e "${Gre}Done${RCol}"
}

BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

git add .
git commit
git push origin "$BRANCH"

echo -e "${BGre}Successfully commited and pushed!${RCol}"
