command_timeout = 1000

add_newline = false

format = """
[█](#383C3E)\
$username\
[](bg:#5A6063 fg:#383C3E)\
$directory\
[](fg:#5A6063 bg:#B0B0B0)\
$nodejs\
[](fg:#B0B0B0 bg:#CFCFCF)\
$python\
[](fg:#CFCFCF bg:#FFFFFF)\
$git_branch\
$git_status\
[ ](fg:#FFFFFF)\
"""

right_format = """
[](fg:#383C3E)\
$localip\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#383C3E"
style_root = "bg:#383C3E"
format = '[ ]($style)'

[directory]
style = "bg:#5A6063"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "fg:black bg:#FFFFFF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:#FFFFFF"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:black bg:#B0B0B0"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:black bg:#CFCFCF"
format = '[ $symbol ($version) ]($style)'

[localip]
ssh_only = false
style = "bg:#383C3E"
format = "[ $localipv4 ]($style)"
disabled = false
